<?php

namespace Database\Seeders;

use App\Models\carModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Sample data for car models
        $models = [
            //toyota models

            ['make_id' => 1, 'name' => '4-Runner'],
            ['make_id' => 1, 'name' => 'Aqua'],
            ['make_id' => 1, 'name' => 'Alphard'],
            ['make_id' => 1, 'name' => 'Allion'],
            ['make_id' => 1, 'name' => 'Allex'],
            ['make_id' => 1, 'name' => 'Altezza'],
            ['make_id' => 1, 'name' => 'Avalon'],
            ['make_id' => 1, 'name' => 'Avanza'],
            ['make_id' => 1, 'name' => 'Avensis'],
            ['make_id' => 1, 'name' => 'Axio'],
            ['make_id' => 1, 'name' => 'Aygo'],
            ['make_id' => 1, 'name' => 'Aristo'],
            ['make_id' => 1, 'name' => 'Aurion'],
            ['make_id' => 1, 'name' => 'Auris'],
            ['make_id' => 1, 'name' => 'bB'],
            ['make_id' => 1, 'name' => 'Belta'],
            ['make_id' => 1, 'name' => 'Blade'],
            ['make_id' => 1, 'name' => 'Brevis'],
            ['make_id' => 1, 'name' => 'bZ3'],
            ['make_id' => 1, 'name' => 'bZ4X'],
            ['make_id' => 1, 'name' => 'C-HR'],
            ['make_id' => 1, 'name' => 'Cami'],
            ['make_id' => 1, 'name' => 'Camry'],
            ['make_id' => 1, 'name' => 'Carib'],
            ['make_id' => 1, 'name' => 'Carina'],
            ['make_id' => 1, 'name' => 'Carina E'],
            ['make_id' => 1, 'name' => 'Caldina'],
            ['make_id' => 1, 'name' => 'Cavalier'],
            ['make_id' => 1, 'name' => 'Celica'],
            ['make_id' => 1, 'name' => 'Chaser'],
            ['make_id' => 1, 'name' => 'Coaster'],
            ['make_id' => 1, 'name' => 'Corolla'],
            ['make_id' => 1, 'name' => 'Corolla Altis'],
            ['make_id' => 1, 'name' => 'Corolla Ceres'],
            ['make_id' => 1, 'name' => 'Corolla Cross'],
            ['make_id' => 1, 'name' => 'Corolla Fielder'],
            ['make_id' => 1, 'name' => 'Corolla 11'],
            ['make_id' => 1, 'name' => 'Corolla Rumion'],
            ['make_id' => 1, 'name' => 'Corolla RunX'],
            ['make_id' => 1, 'name' => 'Corolla Spacio'],
            ['make_id' => 1, 'name' => 'Corolla Verso'],
            ['make_id' => 1, 'name' => 'Corona'],
            ['make_id' => 1, 'name' => 'Corona Exiv'],
            ['make_id' => 1, 'name' => 'Corona Premio'],
            ['make_id' => 1, 'name' => 'Corsa'],
            ['make_id' => 1, 'name' => 'Cressida'],
            ['make_id' => 1, 'name' => 'Cresta'],
            ['make_id' => 1, 'name' => 'Crown'],
            ['make_id' => 1, 'name' => 'Crown Majesta'],
            ['make_id' => 1, 'name' => 'Curren'],
            ['make_id' => 1, 'name' => 'Cynos'],
            ['make_id' => 1, 'name' => 'Duet'],
            ['make_id' => 1, 'name' => 'Dyna'],
            ['make_id' => 1, 'name' => 'Echo'],
            ['make_id' => 1, 'name' => 'Esquire'],
            ['make_id' => 1, 'name' => 'Estima'],
            ['make_id' => 1, 'name' => 'FJ Cruiser'],
            ['make_id' => 1, 'name' => 'Fortuner'],
            ['make_id' => 1, 'name' => 'Fun Cargo'],
            ['make_id' => 1, 'name' => 'Gaia'],
            ['make_id' => 1, 'name' => 'Grand Highlander'],
            ['make_id' => 1, 'name' => 'Granvia'],
            ['make_id' => 1, 'name' => 'GT86'],
            ['make_id' => 1, 'name' => 'Harrier'],
            ['make_id' => 1, 'name' => 'HiAce'],
            ['make_id' => 1, 'name' => 'Highlander'],
            ['make_id' => 1, 'name' => 'Hilux'],
            ['make_id' => 1, 'name' => 'Innova'],
            ['make_id' => 1, 'name' => 'Ipsum'],
            ['make_id' => 1, 'name' => 'iQ'],
            ['make_id' => 1, 'name' => 'ISIS'],
            ['make_id' => 1, 'name' => 'IST'],
            ['make_id' => 1, 'name' => 'Kluger'],
            ['make_id' => 1, 'name' => 'Land Cruiser'],
            ['make_id' => 1, 'name' => 'Land Cruiser Prado'],
            ['make_id' => 1, 'name' => 'Land Cruiser Cygnus'],
            ['make_id' => 1, 'name' => 'Lexcen'],
            ['make_id' => 1, 'name' => 'Lite-Ace'],
            ['make_id' => 1, 'name' => 'Mark II'],
            ['make_id' => 1, 'name' => 'Mark II Blitt'],
            ['make_id' => 1, 'name' => 'Mark II Qualis'],
            ['make_id' => 1, 'name' => 'Mark X'],
            ['make_id' => 1, 'name' => 'Mark X Zio'],
            ['make_id' => 1, 'name' => 'Matrix'],
            ['make_id' => 1, 'name' => 'Mirai'],
            ['make_id' => 1, 'name' => 'MR-S'],
            ['make_id' => 1, 'name' => 'MR2'],
            ['make_id' => 1, 'name' => 'Nadia'],
            ['make_id' => 1, 'name' => 'Noah'],
            ['make_id' => 1, 'name' => 'Opa'],
            ['make_id' => 1, 'name' => 'Paseo'],
            ['make_id' => 1, 'name' => 'Passo'],
            ['make_id' => 1, 'name' => 'Passo Sette'],
            ['make_id' => 1, 'name' => 'Picnic'],
            ['make_id' => 1, 'name' => 'Pixis'],
            ['make_id' => 1, 'name' => 'Pixis Epoch'],
            ['make_id' => 1, 'name' => 'Pixis Joy'],
            ['make_id' => 1, 'name' => 'Pixis Mega'],
            ['make_id' => 1, 'name' => 'Pixis Space'],
            ['make_id' => 1, 'name' => 'Platz'],
            ['make_id' => 1, 'name' => 'Porte'],
            ['make_id' => 1, 'name' => 'Premio'],
            ['make_id' => 1, 'name' => 'Previa'],
            ['make_id' => 1, 'name' => 'Prius'],
            ['make_id' => 1, 'name' => 'Probox'],
            ['make_id' => 1, 'name' => 'Progress'],
            ['make_id' => 1, 'name' => 'Ractis'],
            ['make_id' => 1, 'name' => 'Raize'],
            ['make_id' => 1, 'name' => 'Raum'],
            ['make_id' => 1, 'name' => 'RAV4'],
            ['make_id' => 1, 'name' => 'Roomy'],
            ['make_id' => 1, 'name' => 'Rumion'],
            ['make_id' => 1, 'name' => 'Rush'],
            ['make_id' => 1, 'name' => 'Sai'],
            ['make_id' => 1, 'name' => 'Scepter'],
            ['make_id' => 1, 'name' => 'Sequoia'],
            ['make_id' => 1, 'name' => 'Sera'],
            ['make_id' => 1, 'name' => 'Sienna'],
            ['make_id' => 1, 'name' => 'Sienta'],
            ['make_id' => 1, 'name' => 'Soarer'],
            ['make_id' => 1, 'name' => 'Solara'],
            ['make_id' => 1, 'name' => 'Spade'],
            ['make_id' => 1, 'name' => 'Sprinter'],
            ['make_id' => 1, 'name' => 'Stallion'],
            ['make_id' => 1, 'name' => 'Starlet'],
            ['make_id' => 1, 'name' => 'Succeed'],
            ['make_id' => 1, 'name' => 'Supra'],
            ['make_id' => 1, 'name' => 'T100'],
            ['make_id' => 1, 'name' => 'Tacoma'],
            ['make_id' => 1, 'name' => 'Tank'],
            ['make_id' => 1, 'name' => 'Tazz'],
            ['make_id' => 1, 'name' => 'Tercel'],
            ['make_id' => 1, 'name' => 'TownAce'],
            ['make_id' => 1, 'name' => 'Toyoace'],
            ['make_id' => 1, 'name' => 'Tundra'],
            ['make_id' => 1, 'name' => 'Urban Cruiser'],
            ['make_id' => 1, 'name' => 'Vanguard'],
            ['make_id' => 1, 'name' => 'Velfire'],
            ['make_id' => 1, 'name' => 'Venture'],
            ['make_id' => 1, 'name' => 'Venza'],
            ['make_id' => 1, 'name' => 'Verossa'],
            ['make_id' => 1, 'name' => 'Verso'],
            ['make_id' => 1, 'name' => 'Vios'],
            ['make_id' => 1, 'name' => 'Vista'],
            ['make_id' => 1, 'name' => 'Vitz'],
            ['make_id' => 1, 'name' => 'Voltz'],
            ['make_id' => 1, 'name' => 'Voxy'],
            ['make_id' => 1, 'name' => 'Will'],
            ['make_id' => 1, 'name' => 'Will VS'],
            ['make_id' => 1, 'name' => 'Wish'],
            ['make_id' => 1, 'name' => 'Yaris'],
            ['make_id' => 1, 'name' => 'Yaris Cross'],

            // honda cars
            ['make_id' => 2, 'name' => 'Accord'],
            ['make_id' => 2, 'name' => 'Accord Crosstour'],
            ['make_id' => 2, 'name' => 'Acty'],
            ['make_id' => 2, 'name' => 'Airwave'],
            ['make_id' => 2, 'name' => 'Avancier'],
            ['make_id' => 2, 'name' => 'Ballade'],
            ['make_id' => 2, 'name' => 'Capa'],
            ['make_id' => 2, 'name' => 'City'],
            ['make_id' => 2, 'name' => 'Civix'],
            ['make_id' => 2, 'name' => 'Concerto'],
            ['make_id' => 2, 'name' => 'CR-V'],
            ['make_id' => 2, 'name' => 'CR-X'],
            ['make_id' => 2, 'name' => 'Crossroad'],
            ['make_id' => 2, 'name' => 'Crosstour'],
            ['make_id' => 2, 'name' => 'Element'],
            ['make_id' => 2, 'name' => 'Elysion'],
            ['make_id' => 2, 'name' => 'Fit'],
            ['make_id' => 2, 'name' => 'Fit Shuttle'],
            ['make_id' => 2, 'name' => 'FR-V'],
            ['make_id' => 2, 'name' => 'Freed'],
            ['make_id' => 2, 'name' => 'Grace'],
            ['make_id' => 2, 'name' => 'HR-V'],
            ['make_id' => 2, 'name' => 'Insight'],
            ['make_id' => 2, 'name' => 'Jade'],
            ['make_id' => 2, 'name' => 'Legend'],
            ['make_id' => 2, 'name' => 'Life'],
            ['make_id' => 2, 'name' => 'Mobio'],
            ['make_id' => 2, 'name' => 'N-Box'],
            ['make_id' => 2, 'name' => 'N-One'],
            ['make_id' => 2, 'name' => 'N-WGN'],
            ['make_id' => 2, 'name' => 'Odyssey'],
            ['make_id' => 2, 'name' => 'Orthia'],
            ['make_id' => 2, 'name' => 'Partner'],
            ['make_id' => 2, 'name' => 'Passport'],
            ['make_id' => 2, 'name' => 'Pilot'],
            ['make_id' => 2, 'name' => 'Prelude'],
            ['make_id' => 2, 'name' => 'Ridgeline'],
            ['make_id' => 2, 'name' => 'S-MX'],
            ['make_id' => 2, 'name' => 'S2000'],
            ['make_id' => 2, 'name' => 'Shuttle'],
            ['make_id' => 2, 'name' => 'Stepwagon'],
            ['make_id' => 2, 'name' => 'Stream'],
            ['make_id' => 2, 'name' => 'Torneo'],
            ['make_id' => 2, 'name' => 'Vamos'],
            ['make_id' => 2, 'name' => 'Vezel'],
            ['make_id' => 2, 'name' => 'Vigor'],

            // subaru cars

            ['make_id' => 3, 'name' => 'Alfa'],
            ['make_id' => 3, 'name' => 'Ascent'],
            ['make_id' => 3, 'name' => 'Baja'],
            ['make_id' => 3, 'name' => 'BRZ'],
            ['make_id' => 3, 'name' => 'Crosstrek Hybrid'],
            ['make_id' => 3, 'name' => 'DL'],
            ['make_id' => 3, 'name' => 'Exiga'],
            ['make_id' => 3, 'name' => 'Forester'],
            ['make_id' => 3, 'name' => 'Impreza'],
            ['make_id' => 3, 'name' => 'Justy'],
            ['make_id' => 3, 'name' => 'Legacy'],
            ['make_id' => 3, 'name' => 'Levorg'],
            ['make_id' => 3, 'name' => 'Liberty'],
            ['make_id' => 3, 'name' => 'Mini'],
            ['make_id' => 3, 'name' => 'Outback'],
            ['make_id' => 3, 'name' => 'Pleo'],
            ['make_id' => 3, 'name' => 'R2'],
            ['make_id' => 3, 'name' => 'Stella'],
            ['make_id' => 3, 'name' => 'SVX'],
            ['make_id' => 3, 'name' => 'Trezia'],
            ['make_id' => 3, 'name' => 'Tribeca'],
            ['make_id' => 3, 'name' => 'Vivio'],
            ['make_id' => 3, 'name' => 'VX Crosstrek'],
            ['make_id' => 3, 'name' => 'WRX'],
            ['make_id' => 3, 'name' => 'WRX STI'],
            ['make_id' => 3, 'name' => 'XVCrosstrek Hybrid'],



            // mazda cars


            ['make_id' => 4, 'name' => 'AZ'],
            ['make_id' => 4, 'name' => 'Axela'],
            ['make_id' => 4, 'name' => 'Atenza'],
            ['make_id' => 4, 'name' => 'B'],
            ['make_id' => 4, 'name' => 'B-SERIES'],
            ['make_id' => 4, 'name' => 'Biante'],
            ['make_id' => 4, 'name' => 'Bongo'],
            ['make_id' => 4, 'name' => 'BT-50'],
            ['make_id' => 4, 'name' => 'Capella'],
            ['make_id' => 4, 'name' => 'Carol'],
            ['make_id' => 4, 'name' => 'Chante'],
            ['make_id' => 4, 'name' => 'Cosmo'],
            ['make_id' => 4, 'name' => 'CX-3'],
            ['make_id' => 4, 'name' => 'CX-5'],
            ['make_id' => 4, 'name' => 'CX-30'],
            ['make_id' => 4, 'name' => 'CX-50'],
            ['make_id' => 4, 'name' => 'CX-60'],
            ['make_id' => 4, 'name' => 'CX-7'],
            ['make_id' => 4, 'name' => 'CX-8'],
            ['make_id' => 4, 'name' => 'CX-90'],
            ['make_id' => 4, 'name' => 'Demio'],
            ['make_id' => 4, 'name' => 'Drifter'],
            ['make_id' => 4, 'name' => 'Efini MPV'],
            ['make_id' => 4, 'name' => 'Efini MS-6'],
            ['make_id' => 4, 'name' => 'Efini MS-8'],
            ['make_id' => 4, 'name' => 'Efini MS-9'],
            ['make_id' => 4, 'name' => 'Efini RX-7'],
            ['make_id' => 4, 'name' => 'Etude'],
            ['make_id' => 4, 'name' => 'Eunos'],
            ['make_id' => 4, 'name' => 'Familia'],
            ['make_id' => 4, 'name' => 'Flair'],
            ['make_id' => 4, 'name' => 'Lantis'],
            ['make_id' => 4, 'name' => 'Laputa'],
            ['make_id' => 4, 'name' => 'Levante'],
            ['make_id' => 4, 'name' => 'Marathon'],
            ['make_id' => 4, 'name' => 'Midge'],
            ['make_id' => 4, 'name' => 'Millenia'],
            ['make_id' => 4, 'name' => 'MPV'],
            ['make_id' => 4, 'name' => 'MS-6'],
            ['make_id' => 4, 'name' => 'MS-8'],
            ['make_id' => 4, 'name' => 'MS-9'],
            ['make_id' => 4, 'name' => 'MX-3'],
            ['make_id' => 4, 'name' => 'MX-5'],
            ['make_id' => 4, 'name' => 'MX-6'],
            ['make_id' => 4, 'name' => 'Persona'],
            ['make_id' => 4, 'name' => 'Premacy'],
            ['make_id' => 4, 'name' => 'Protege'],
            ['make_id' => 4, 'name' => 'R-100'],
            ['make_id' => 4, 'name' => 'R360'],
            ['make_id' => 4, 'name' => 'Rustler'],
            ['make_id' => 4, 'name' => 'RX-2'],
            ['make_id' => 4, 'name' => 'RX-3'],
            ['make_id' => 4, 'name' => 'RX-4'],
            ['make_id' => 4, 'name' => 'RX-7'],
            ['make_id' => 4, 'name' => 'RX-8'],
            ['make_id' => 4, 'name' => 'Scrum'],
            ['make_id' => 4, 'name' => 'Sentia'],
            ['make_id' => 4, 'name' => 'Spiano'],
            ['make_id' => 4, 'name' => 'Titan Dash'],
            ['make_id' => 4, 'name' => 'Tribute'],
            ['make_id' => 4, 'name' => 'Versia'],
            ['make_id' => 4, 'name' => 'Washu'],
            ['make_id' => 4, 'name' => 'Xedos'],
            ['make_id' => 4, 'name' => '1000'],
            ['make_id' => 4, 'name' => '110'],
            ['make_id' => 4, 'name' => '121'],
            ['make_id' => 4, 'name' => '2'],
            ['make_id' => 4, 'name' => '3'],
            ['make_id' => 4, 'name' => '323'],
            ['make_id' => 4, 'name' => '5'],
            ['make_id' => 4, 'name' => '6'],
            ['make_id' => 4, 'name' => '616'],
            ['make_id' => 4, 'name' => '626'],
            ['make_id' => 4, 'name' => '787'],
            ['make_id' => 4, 'name' => '818'],
            ['make_id' => 4, 'name' => '929'],

            // BMW CARS

            ['make_id' => 5, 'name' => '1series'],
            ['make_id' => 5, 'name' => '116i'],
            ['make_id' => 5, 'name' => '118d'],
            ['make_id' => 5, 'name' => '118i'],
            ['make_id' => 5, 'name' => '120d'],
            ['make_id' => 5, 'name' => '120i'],
            ['make_id' => 5, 'name' => '125i'],
            ['make_id' => 5, 'name' => '128i'],
            ['make_id' => 5, 'name' => '130i'],
            ['make_id' => 5, 'name' => '135i'],
            ['make_id' => 5, 'name' => '2002'],
            ['make_id' => 5, 'name' => '214d'],
            ['make_id' => 5, 'name' => '216d'],
            ['make_id' => 5, 'name' => '216i'],
            ['make_id' => 5, 'name' => '218i'],
            ['make_id' => 5, 'name' => '220d'],
            ['make_id' => 5, 'name' => '220i'],
            ['make_id' => 5, 'name' => '225d'],
            ['make_id' => 5, 'name' => '225i'],
            ['make_id' => 5, 'name' => '225xe'],
            ['make_id' => 5, 'name' => '228i'],
            ['make_id' => 5, 'name' => '230i'],
            ['make_id' => 5, 'name' => '3 series'],
            ['make_id' => 5, 'name' => '316Ti'],
            ['make_id' => 5, 'name' => '316i'],
            ['make_id' => 5, 'name' => '318ti'],
            ['make_id' => 5, 'name' => '320Ci'],
            ['make_id' => 5, 'name' => '320i'],
            ['make_id' => 5, 'name' => '323i'],
            ['make_id' => 5, 'name' => '325i'],
            ['make_id' => 5, 'name' => '328i'],
            ['make_id' => 5, 'name' => '330i'],
            ['make_id' => 5, 'name' => '333i'],
            ['make_id' => 5, 'name' => '335i'],
            ['make_id' => 5, 'name' => '4 Series'],
            ['make_id' => 5, 'name' => '420d'],
            ['make_id' => 5, 'name' => '450'],
            ['make_id' => 5, 'name' => '5 Series'],
            ['make_id' => 5, 'name' => '518i'],
            ['make_id' => 5, 'name' => '520i'],
            ['make_id' => 5, 'name' => '523i'],
            ['make_id' => 5, 'name' => '524d'],
            ['make_id' => 5, 'name' => '525i'],
            ['make_id' => 5, 'name' => '528i'],
            ['make_id' => 5, 'name' => '535d'],
            ['make_id' => 5, 'name' => '535i'],
            ['make_id' => 5, 'name' => '540i'],
            ['make_id' => 5, 'name' => '550i'],
            ['make_id' => 5, 'name' => '6 Series'],
            ['make_id' => 5, 'name' => '7 Series'],
            ['make_id' => 5, 'name' => '8 Series'],
            ['make_id' => 5, 'name' => 'Alpina B7'],
            ['make_id' => 5, 'name' => 'C1'],
            ['make_id' => 5, 'name' => 'Dinan'],
            ['make_id' => 5, 'name' => 'F-Series'],
            ['make_id' => 5, 'name' => 'F650GS'],
            ['make_id' => 5, 'name' => 'F800'],
            ['make_id' => 5, 'name' => 'FW'],
            ['make_id' => 5, 'name' => 'G-Series'],
            ['make_id' => 5, 'name' => 'HP2'],
            ['make_id' => 5, 'name' => 'i3'],
            ['make_id' => 5, 'name' => 'i8'],
            ['make_id' => 5, 'name' => 'Isetta'],
            ['make_id' => 5, 'name' => 'Just'],
            ['make_id' => 5, 'name' => 'K-Series'],
            ['make_id' => 5, 'name' => 'Karmann'],
            ['make_id' => 5, 'name' => 'L7'],
            ['make_id' => 5, 'name' => 'LMR'],
            ['make_id' => 5, 'name' => 'Lo'],
            ['make_id' => 5, 'name' => 'M1'],
            ['make_id' => 5, 'name' => 'M2'],
            ['make_id' => 5, 'name' => 'M3'],
            ['make_id' => 5, 'name' => 'M4'],
            ['make_id' => 5, 'name' => 'M5'],
            ['make_id' => 5, 'name' => 'M6'],
            ['make_id' => 5, 'name' => 'M7'],
            ['make_id' => 5, 'name' => 'MM'],
            ['make_id' => 5, 'name' => 'R-Series'],
            ['make_id' => 5, 'name' => 'R65'],
            ['make_id' => 5, 'name' => 'S-Series'],
            ['make_id' => 5, 'name' => 'S3'],
            ['make_id' => 5, 'name' => 'Veritas'],
            ['make_id' => 5, 'name' => 'X1'],
            ['make_id' => 5, 'name' => 'X2'],
            ['make_id' => 5, 'name' => 'X3'],
            ['make_id' => 5, 'name' => 'X4'],
            ['make_id' => 5, 'name' => 'X5'],
            ['make_id' => 5, 'name' => 'X6'],
            ['make_id' => 5, 'name' => 'X7'],
            ['make_id' => 5, 'name' => 'Z1'],
            ['make_id' => 5, 'name' => 'Z3'],
            ['make_id' => 5, 'name' => 'Z4'],



            // Mercedes-Benz cars
            ['make_id' => 6, 'name' => 'C200'],
            ['make_id' => 6, 'name' => 'GLE-Class'],
            ['make_id' => 6, 'name' => 'GLC-Class'],
            ['make_id' => 6, 'name' => 'E250'],
            ['make_id' => 6, 'name' => 'E200'],
            ['make_id' => 6, 'name' => '1113'],
            ['make_id' => 6, 'name' => '1117'],
            ['make_id' => 6, 'name' => '1420'],
            ['make_id' => 6, 'name' => '1422'],
            ['make_id' => 6, 'name' => '1619'],
            ['make_id' => 6, 'name' => '1622'],
            ['make_id' => 6, 'name' => '1722'],
            ['make_id' => 6, 'name' => '1733'],
            ['make_id' => 6, 'name' => '1820'],
            ['make_id' => 6, 'name' => '1824'],
            ['make_id' => 6, 'name' => '1827'],
            ['make_id' => 6, 'name' => '190'],
            ['make_id' => 6, 'name' => '190E'],
            ['make_id' => 6, 'name' => '1922'],
            ['make_id' => 6, 'name' => '1927'],
            ['make_id' => 6, 'name' => '200'],
            ['make_id' => 6, 'name' => '200E'],
            ['make_id' => 6, 'name' => '2024'],
            ['make_id' => 6, 'name' => '220'],
            ['make_id' => 6, 'name' => '220E'],
            ['make_id' => 6, 'name' => '230E'],
            ['make_id' => 6, 'name' => '2422'],
            ['make_id' => 6, 'name' => '2524'],
            ['make_id' => 6, 'name' => '260E'],
            ['make_id' => 6, 'name' => '280E'],
            ['make_id' => 6, 'name' => '300D'],
            ['make_id' => 6, 'name' => '300E'],
            ['make_id' => 6, 'name' => '300TE'],
            ['make_id' => 6, 'name' => '350D'],
            ['make_id' => 6, 'name' => '500SE'],
            ['make_id' => 6, 'name' => 'A-Class'],
            ['make_id' => 6, 'name' => 'B-Class'],
            ['make_id' => 6, 'name' => 'C-Class'],
            ['make_id' => 6, 'name' => 'C160'],
            ['make_id' => 6, 'name' => 'C180'],
            ['make_id' => 6, 'name' => 'C220'],
            ['make_id' => 6, 'name' => 'C230'],
            ['make_id' => 6, 'name' => 'C240'],
            ['make_id' => 6, 'name' => 'C250'],
            ['make_id' => 6, 'name' => 'C270'],
            ['make_id' => 6, 'name' => 'C280'],
            ['make_id' => 6, 'name' => 'C300'],
            ['make_id' => 6, 'name' => 'C320'],
            ['make_id' => 6, 'name' => 'C350'],
            ['make_id' => 6, 'name' => 'C400'],
            ['make_id' => 6, 'name' => 'C43'],
            ['make_id' => 6, 'name' => 'C63'],
            ['make_id' => 6, 'name' => 'Ciataro'],
            ['make_id' => 6, 'name' => 'Cito'],
            ['make_id' => 6, 'name' => 'CL'],
            ['make_id' => 6, 'name' => 'CLA-CLASS'],
            ['make_id' => 6, 'name' => 'CLC'],
            ['make_id' => 6, 'name' => 'CLK'],
            ['make_id' => 6, 'name' => 'CLS'],
            ['make_id' => 6, 'name' => 'Connecto'],
            ['make_id' => 6, 'name' => 'E220'],
            ['make_id' => 6, 'name' => 'E230'],
            ['make_id' => 6, 'name' => 'E240'],
            ['make_id' => 6, 'name' => 'E270'],
            ['make_id' => 6, 'name' => 'E280'],
            ['make_id' => 6, 'name' => 'E300'],
            ['make_id' => 6, 'name' => 'E320'],
            ['make_id' => 6, 'name' => 'E350'],
            ['make_id' => 6, 'name' => 'E350e'],
            ['make_id' => 6, 'name' => 'E400'],
            ['make_id' => 6, 'name' => 'E420'],
            ['make_id' => 6, 'name' => 'E43 AMG'],
            ['make_id' => 6, 'name' => 'E430'],
            ['make_id' => 6, 'name' => 'E450'],
            ['make_id' => 6, 'name' => 'E500'],
            ['make_id' => 6, 'name' => 'E53 AMG'],
            ['make_id' => 6, 'name' => 'E55'],
            ['make_id' => 6, 'name' => 'E550'],
            ['make_id' => 6, 'name' => 'E63'],
            ['make_id' => 6, 'name' => 'EB'],
            ['make_id' => 6, 'name' => 'EQC'],
            ['make_id' => 6, 'name' => 'EQE'],
            ['make_id' => 6, 'name' => 'G-Class'],
            ['make_id' => 6, 'name' => 'GL-Class'],
            ['make_id' => 6, 'name' => 'GLA 250'],
            ['make_id' => 6, 'name' => 'GLA-Class'],
            ['make_id' => 6, 'name' => 'GLB-Class'],
            ['make_id' => 6, 'name' => 'GLE43'],
            ['make_id' => 6, 'name' => 'GLE53'],
            ['make_id' => 6, 'name' => 'GLK-Class'],
            ['make_id' => 6, 'name' => 'GLS-Class'],
            ['make_id' => 6, 'name' => 'Intouro'],
            ['make_id' => 6, 'name' => 'M Class'],
            ['make_id' => 6, 'name' => 'MB100'],
            ['make_id' => 6, 'name' => 'Metris'],
            ['make_id' => 6, 'name' => 'Ponton'],
            ['make_id' => 6, 'name' => 'R-Class'],
            ['make_id' => 6, 'name' => 'S-Class'],
            ['make_id' => 6, 'name' => 'SC-Class'],
            ['make_id' => 6, 'name' => 'SL-Class'],
            ['make_id' => 6, 'name' => 'SLK-Class'],
            ['make_id' => 6, 'name' => 'SLR-Class'],
            ['make_id' => 6, 'name' => 'SLS AMG'],
            ['make_id' => 6, 'name' => 'Sprinter'],
            ['make_id' => 6, 'name' => 'TN'],
            ['make_id' => 6, 'name' => 'Travego'],
            ['make_id' => 6, 'name' => 'Vaneo'],
            ['make_id' => 6, 'name' => 'Viano'],
            ['make_id' => 6, 'name' => 'Vito'],
            ['make_id' => 6, 'name' => 'VS680L Mayback'],
            ['make_id' => 6, 'name' => 'W123'],
            ['make_id' => 6, 'name' => 'W124'],
            ['make_id' => 6, 'name' => 'X-Class'],

            // Audi cars

            ['make_id' => 7, 'name' => '100'],
            ['make_id' => 7, 'name' => '200'],
            ['make_id' => 7, 'name' => '4000'],
            ['make_id' => 7, 'name' => '50'],
            ['make_id' => 7, 'name' => '5000'],
            ['make_id' => 7, 'name' => '80'],
            ['make_id' => 7, 'name' => '90'],
            ['make_id' => 7, 'name' => 'A1'],
            ['make_id' => 7, 'name' => 'A2'],
            ['make_id' => 7, 'name' => 'A3'],
            ['make_id' => 7, 'name' => 'A4'],
            ['make_id' => 7, 'name' => 'A5'],
            ['make_id' => 7, 'name' => 'A6'],
            ['make_id' => 7, 'name' => 'A7'],
            ['make_id' => 7, 'name' => 'A8'],
            ['make_id' => 7, 'name' => 'Allroad'],
            ['make_id' => 7, 'name' => 'Q2'],
            ['make_id' => 7, 'name' => 'Q3'],
            ['make_id' => 7, 'name' => 'Q5'],
            ['make_id' => 7, 'name' => 'Q7'],
            ['make_id' => 7, 'name' => 'Q8'],
            ['make_id' => 7, 'name' => 'Quattro'],
            ['make_id' => 7, 'name' => 'R8'],
            ['make_id' => 7, 'name' => 'RS 6'],
            ['make_id' => 7, 'name' => 'RS 7'],
            ['make_id' => 7, 'name' => 'S2'],
            ['make_id' => 7, 'name' => 'S3'],
            ['make_id' => 7, 'name' => 'S4'],
            ['make_id' => 7, 'name' => 'S5'],
            ['make_id' => 7, 'name' => 'S6'],
            ['make_id' => 7, 'name' => 'S7'],
            ['make_id' => 7, 'name' => 'S8'],
            ['make_id' => 7, 'name' => 'SQ5'],
            ['make_id' => 7, 'name' => 'TT'],



            // Volkswagen cars
            ['make_id' => 8, 'name' => '1302'],
            ['make_id' => 8, 'name' => '1303'],
            ['make_id' => 8, 'name' => '1500'],
            ['make_id' => 8, 'name' => '1600'],
            ['make_id' => 8, 'name' => '181'],
            ['make_id' => 8, 'name' => '411'],
            ['make_id' => 8, 'name' => 'Aac'],
            ['make_id' => 8, 'name' => 'Amarok'],
            ['make_id' => 8, 'name' => 'Arteon'],
            ['make_id' => 8, 'name' => 'Atlas'],
            ['make_id' => 8, 'name' => 'Atlas Cross Sport'],
            ['make_id' => 8, 'name' => 'Beetle'],
            ['make_id' => 8, 'name' => 'Bora'],
            ['make_id' => 8, 'name' => 'Caddy'],
            ['make_id' => 8, 'name' => 'Caravell'],
            ['make_id' => 8, 'name' => 'CC'],
            ['make_id' => 8, 'name' => 'Citi'],
            ['make_id' => 8, 'name' => 'Corrado'],
            ['make_id' => 8, 'name' => 'Derby'],
            ['make_id' => 8, 'name' => 'E-Golf'],
            ['make_id' => 8, 'name' => 'Eos'],
            ['make_id' => 8, 'name' => 'Eurovan'],
            ['make_id' => 8, 'name' => 'Fox'],
            ['make_id' => 8, 'name' => 'Fusca'],
            ['make_id' => 8, 'name' => 'Golf'],
            ['make_id' => 8, 'name' => 'Golf Alltrack'],
            ['make_id' => 8, 'name' => 'Golf GTI'],
            ['make_id' => 8, 'name' => 'Golf R'],
            ['make_id' => 8, 'name' => 'Golf SportWagen'],
            ['make_id' => 8, 'name' => 'Golf Variant'],
            ['make_id' => 8, 'name' => 'ID.4'],
            ['make_id' => 8, 'name' => '1D.5'],
            ['make_id' => 8, 'name' => '1D.6'],
            ['make_id' => 8, 'name' => 'Iltis'],
            ['make_id' => 8, 'name' => 'Jetta'],
            ['make_id' => 8, 'name' => 'Jetta GLI'],
            ['make_id' => 8, 'name' => 'K70'],
            ['make_id' => 8, 'name' => 'Kombi'],
            ['make_id' => 8, 'name' => 'Lupo'],
            ['make_id' => 8, 'name' => 'Microbus'],
            ['make_id' => 8, 'name' => 'Multivan'],
            ['make_id' => 8, 'name' => 'Parati'],
            ['make_id' => 8, 'name' => 'Passat'],
            ['make_id' => 8, 'name' => 'Phaeton'],
            ['make_id' => 8, 'name' => 'Polo'],
            ['make_id' => 8, 'name' => 'Quantum'],
            ['make_id' => 8, 'name' => 'Rabbit'],
            ['make_id' => 8, 'name' => 'Routan'],
            ['make_id' => 8, 'name' => 'Santana'],
            ['make_id' => 8, 'name' => 'Scirrocco'],
            ['make_id' => 8, 'name' => 'Sharan'],
            ['make_id' => 8, 'name' => 'SP2'],
            ['make_id' => 8, 'name' => 'T-Cross'],
            ['make_id' => 8, 'name' => 'Taos'],
            ['make_id' => 8, 'name' => 'Teramont'],
            ['make_id' => 8, 'name' => 'Tiguan'],
            ['make_id' => 8, 'name' => 'Touareg'],
            ['make_id' => 8, 'name' => 'Touran'],
            ['make_id' => 8, 'name' => 'Transporter'],
            ['make_id' => 8, 'name' => 'Up'],
            ['make_id' => 8, 'name' => 'Vento'],
            // Nissan cars
            ['make_id' => 9, 'name' => '100'],
            ['make_id' => 9, 'name' => '1400'],
            ['make_id' => 9, 'name' => '200SX'],
            ['make_id' => 9, 'name' => '240SX'],
            ['make_id' => 9, 'name' => '260Z'],
            ['make_id' => 9, 'name' => '300ZX'],
            ['make_id' => 9, 'name' => '350Z'],
            ['make_id' => 9, 'name' => '370Z'],
            ['make_id' => 9, 'name' => 'Advan'],
            ['make_id' => 9, 'name' => 'Almera'],
            ['make_id' => 9, 'name' => 'Altima'],
            ['make_id' => 9, 'name' => 'Ariya'],
            ['make_id' => 9, 'name' => 'Armada'],
            ['make_id' => 9, 'name' => 'Atlas'],
            ['make_id' => 9, 'name' => 'Avenir'],
            ['make_id' => 9, 'name' => 'Basara'],
            ['make_id' => 9, 'name' => 'Bluebird'],
            ['make_id' => 9, 'name' => 'Cabstar'],
            ['make_id' => 9, 'name' => 'Caravan'],
            ['make_id' => 9, 'name' => 'Carina'],
            ['make_id' => 9, 'name' => 'Cedric'],
            ['make_id' => 9, 'name' => 'Cefiro'],
            ['make_id' => 9, 'name' => 'Cherry'],
            ['make_id' => 9, 'name' => 'Cima'],
            ['make_id' => 9, 'name' => 'Civilian'],
            ['make_id' => 9, 'name' => 'Commercial'],
            ['make_id' => 9, 'name' => 'Crima'],
            ['make_id' => 9, 'name' => 'Crew'],
            ['make_id' => 9, 'name' => 'Cube'],
            ['make_id' => 9, 'name' => 'Dayz'],
            ['make_id' => 9, 'name' => 'Dayz Roox'],
            ['make_id' => 9, 'name' => 'DoubleCab'],
            ['make_id' => 9, 'name' => 'Dualis'],
            ['make_id' => 9, 'name' => 'E20'],
            ['make_id' => 9, 'name' => 'Elgrand'],
            ['make_id' => 9, 'name' => 'Fairlady'],
            ['make_id' => 9, 'name' => 'FB14'],
            ['make_id' => 9, 'name' => 'FB15'],
            ['make_id' => 9, 'name' => 'Frontier'],
            ['make_id' => 9, 'name' => 'Fuga'],
            ['make_id' => 9, 'name' => 'Fusion'],
            ['make_id' => 9, 'name' => 'Gloria'],
            ['make_id' => 9, 'name' => 'Grand'],
            ['make_id' => 9, 'name' => 'GT-R'],
            ['make_id' => 9, 'name' => 'Hardbody'],
            ['make_id' => 9, 'name' => 'HyperMini'],
            ['make_id' => 9, 'name' => 'Ideo'],
            ['make_id' => 9, 'name' => 'Interstar'],
            ['make_id' => 9, 'name' => 'Juke'],
            ['make_id' => 9, 'name' => 'Kicks'],
            ['make_id' => 9, 'name' => 'Kix'],
            ['make_id' => 9, 'name' => 'Lafesta'],
            ['make_id' => 9, 'name' => 'Latio'],
            ['make_id' => 9, 'name' => 'Laurel'],
            ['make_id' => 9, 'name' => 'Leaf'],
            ['make_id' => 9, 'name' => 'Leopard'],
            ['make_id' => 9, 'name' => 'Liberty'],
            ['make_id' => 9, 'name' => 'Livina'],
            ['make_id' => 9, 'name' => 'March'],
            ['make_id' => 9, 'name' => 'Maxima'],
            ['make_id' => 9, 'name' => 'Micra'],
            ['make_id' => 9, 'name' => 'Moco'],
            ['make_id' => 9, 'name' => 'Murano'],
            ['make_id' => 9, 'name' => 'Navara'],
            ['make_id' => 9, 'name' => 'Note'],
            ['make_id' => 9, 'name' => 'NP200'],
            ['make_id' => 9, 'name' => 'NP300'],
            ['make_id' => 9, 'name' => 'NV100 Clipper'],
            ['make_id' => 9, 'name' => 'NV1500'],
            ['make_id' => 9, 'name' => 'NV200'],
            ['make_id' => 9, 'name' => 'NV3500'],
            ['make_id' => 9, 'name' => 'Otti'],
            ['make_id' => 9, 'name' => 'PathFinder'],
            ['make_id' => 9, 'name' => 'Patrol'],
            ['make_id' => 9, 'name' => 'Pick-Up'],
            ['make_id' => 9, 'name' => 'Pino'],
            ['make_id' => 9, 'name' => 'Pintara'],
            ['make_id' => 9, 'name' => 'Pixo'],
            ['make_id' => 9, 'name' => 'Platina'],
            ['make_id' => 9, 'name' => 'Prairie'],
            ['make_id' => 9, 'name' => 'Presage'],
            ['make_id' => 9, 'name' => 'Presea'],
            ['make_id' => 9, 'name' => 'President'],
            ['make_id' => 9, 'name' => 'Primastar'],
            ['make_id' => 9, 'name' => 'Primera'],
            ['make_id' => 9, 'name' => 'Pulsar'],
            ['make_id' => 9, 'name' => 'Qashqai'],
            ['make_id' => 9, 'name' => 'Quest'],
            ['make_id' => 9, 'name' => 'Rasheem'],
            ['make_id' => 9, 'name' => 'Rogue'],
            ['make_id' => 9, 'name' => 'Rogue Sport'],
            ['make_id' => 9, 'name' => 'Santana'],
            ['make_id' => 9, 'name' => 'Sentra'],
            ['make_id' => 9, 'name' => 'Serena'],
            ['make_id' => 9, 'name' => 'Silvia'],
            ['make_id' => 9, 'name' => 'Skyline'],
            ['make_id' => 9, 'name' => 'Stagea'],
            ['make_id' => 9, 'name' => 'Stanza'],
            ['make_id' => 9, 'name' => 'Sunny'],
            ['make_id' => 9, 'name' => 'Sylphy'],
            ['make_id' => 9, 'name' => 'Teana'],
            ['make_id' => 9, 'name' => 'Terrano'],
            ['make_id' => 9, 'name' => 'Tiida'],
            ['make_id' => 9, 'name' => 'Titan'],
            ['make_id' => 9, 'name' => 'Trailrunner'],
            ['make_id' => 9, 'name' => 'UA-QG'],
            ['make_id' => 9, 'name' => 'UD'],
            ['make_id' => 9, 'name' => 'Vanette'],
            ['make_id' => 9, 'name' => 'Versa'],
            ['make_id' => 9, 'name' => 'Violet'],
            ['make_id' => 9, 'name' => 'Wingroad'],
            ['make_id' => 9, 'name' => 'X-Trail'],
            ['make_id' => 9, 'name' => 'Xterra'],
            // Infiniti cars
            ['make_id' => 10, 'name' => 'QX80'],
            ['make_id' => 10, 'name' => 'QX60'],
            ['make_id' => 10, 'name' => 'QX50'],
            ['make_id' => 10, 'name' => 'QX55'],
            ['make_id' => 10, 'name' => 'QX60'],
            ['make_id' => 10, 'name' => 'QX80'],

            // Mitsubushi cars
            ['make_id' => 11, 'name' => 'Delica'],
            ['make_id' => 11, 'name' => 'Mirage'],
            ['make_id' => 11, 'name' => 'Outlander'],
            ['make_id' => 11, 'name' => 'Pajero'],
            ['make_id' => 11, 'name' => 'RVR'],
            ['make_id' => 11, 'name' => 'Airtrek'],
            ['make_id' => 11, 'name' => 'ASX'],
            ['make_id' => 11, 'name' => 'Canter'],
            ['make_id' => 11, 'name' => 'Colt'],
            ['make_id' => 11, 'name' => 'Colt Plus'],
            ['make_id' => 11, 'name' => 'Dion'],
            ['make_id' => 11, 'name' => 'Eclipse Cross'],
            ['make_id' => 11, 'name' => 'EK'],
            ['make_id' => 11, 'name' => 'EK Sport'],
            ['make_id' => 11, 'name' => 'EK Wagon'],
            ['make_id' => 11, 'name' => 'Fuso'],
            ['make_id' => 11, 'name' => 'Galant'],
            ['make_id' => 11, 'name' => 'L200'],
            ['make_id' => 11, 'name' => 'Lancer'],
            ['make_id' => 11, 'name' => 'Lancer Cargo'],
            ['make_id' => 11, 'name' => 'Lancer Cedia'],
            ['make_id' => 11, 'name' => 'Legnam'],
            ['make_id' => 11, 'name' => 'Minica'],
            ['make_id' => 11, 'name' => 'Outlander Sport'],
            ['make_id' => 11, 'name' => 'Pajero IO'],
            ['make_id' => 11, 'name' => 'Pajero Sport'],
            ['make_id' => 11, 'name' => 'Shogun'],
            ['make_id' => 11, 'name' => 'SpaceWagon'],
            ['make_id' => 11, 'name' => 'Warrior'],

            // Volvo cars
            ['make_id' => 12, 'name' => '240'],
            ['make_id' => 12, 'name' => '940'],
            ['make_id' => 12, 'name' => 'S60'],
            ['make_id' => 12, 'name' => 'S80'],
            ['make_id' => 12, 'name' => 'S90'],
            ['make_id' => 12, 'name' => 'V40'],
            ['make_id' => 12, 'name' => 'V60'],
            ['make_id' => 12, 'name' => 'V70'],
            ['make_id' => 12, 'name' => 'XC40'],
            ['make_id' => 12, 'name' => 'XC60'],
            ['make_id' => 12, 'name' => 'XC90'],

            // Lexus cars
            ['make_id' => 13, 'name' => 'CT'],
            ['make_id' => 13, 'name' => 'ES'],
            ['make_id' => 13, 'name' => 'GS'],
            ['make_id' => 13, 'name' => 'GX'],
            ['make_id' => 13, 'name' => 'HS'],
            ['make_id' => 13, 'name' => 'IS'],
            ['make_id' => 13, 'name' => 'LC'],
            ['make_id' => 13, 'name' => 'LS'],
            ['make_id' => 13, 'name' => 'LX'],
            ['make_id' => 13, 'name' => 'NX'],
            ['make_id' => 13, 'name' => 'NX 300h'],
            ['make_id' => 13, 'name' => 'RC'],
            ['make_id' => 13, 'name' => 'RX'],
            ['make_id' => 13, 'name' => 'RX 200'],
            ['make_id' => 13, 'name' => 'RX 270'],
            ['make_id' => 13, 'name' => 'RX 300'],
            ['make_id' => 13, 'name' => 'RX 330'],
            ['make_id' => 13, 'name' => 'RX 350'],
            ['make_id' => 13, 'name' => 'RX 400h'],
            ['make_id' => 13, 'name' => 'RX 450h'],
            ['make_id' => 13, 'name' => 'SC'],
            ['make_id' => 13, 'name' => 'TX'],
            ['make_id' => 13, 'name' => 'UX'],
            // LandRover cars
            ['make_id' => 14, 'name' => 'Defender'],
            ['make_id' => 14, 'name' => 'Discovery'],
            ['make_id' => 14, 'name' => 'Discovery Sport'],
            ['make_id' => 14, 'name' => 'Freelander'],
            ['make_id' => 14, 'name' => 'Lr3'],
            ['make_id' => 14, 'name' => 'Lr4'],
            ['make_id' => 14, 'name' => 'Range Rover'],
            ['make_id' => 14, 'name' => 'Range Rover Evoque'],
            ['make_id' => 14, 'name' => 'Range Rover Sport'],
            ['make_id' => 14, 'name' => 'Range Rover Velar'],
            ['make_id' => 14, 'name' => 'Range Rover Vogue'],
            ['make_id' => 14, 'name' => 'Series'],

            // Jaguar cars
            ['make_id' => 15, 'name' => 'E-Pace'],
            ['make_id' => 15, 'name' => 'F-Pace'],
            ['make_id' => 15, 'name' => 'F-Type'],
            ['make_id' => 15, 'name' => 'I-Pace'],
            ['make_id' => 15, 'name' => 'S-Type'],
            ['make_id' => 15, 'name' => 'XE'],
            ['make_id' => 15, 'name' => 'XF'],
            ['make_id' => 15, 'name' => 'XJ'],
            ['make_id' => 15, 'name' => 'XK'],
            // Jeep cars
            ['make_id' => 16, 'name' => 'Cherokee'],
            ['make_id' => 16, 'name' => 'Commander'],
            ['make_id' => 16, 'name' => 'Compass'],
            ['make_id' => 16, 'name' => 'Gladiator'],
            ['make_id' => 16, 'name' => 'Grand Cherokee'],
            ['make_id' => 16, 'name' => 'Liberty'],
            ['make_id' => 16, 'name' => 'Patriot'],
            ['make_id' => 16, 'name' => 'Renegade'],
            ['make_id' => 16, 'name' => 'Wrangler'],
            // Porsche cars
            ['make_id' => 17, 'name' => '911'],
            ['make_id' => 17, 'name' => 'Cayenne'],
            ['make_id' => 17, 'name' => 'Macan'],
            ['make_id' => 17, 'name' => 'Panamera'],

            // Ford cars
            ['make_id' => 18, 'name' => 'Ecosport'],
            ['make_id' => 18, 'name' => 'Escape'],
            ['make_id' => 18, 'name' => 'Everest'],
            ['make_id' => 18, 'name' => 'Kuga'],
            ['make_id' => 18, 'name' => 'Ranger'],
            ['make_id' => 18, 'name' => 'Escort'],
            ['make_id' => 18, 'name' => 'Explorer'],
            ['make_id' => 18, 'name' => 'F-150'],
            ['make_id' => 18, 'name' => 'F-250'],
            ['make_id' => 18, 'name' => 'Fiesta'],
            ['make_id' => 18, 'name' => 'Focus'],
            ['make_id' => 18, 'name' => 'Fusion'],
            ['make_id' => 18, 'name' => 'Galaxy'],
            ['make_id' => 18, 'name' => 'Mondeo'],
            ['make_id' => 18, 'name' => 'Mustang'],
            ['make_id' => 18, 'name' => 'S-Max'],
            ['make_id' => 18, 'name' => 'Sport Trac'],


            // Chevrolet cars
            ['make_id' => 19, 'name' => 'Aveo'],
            ['make_id' => 19, 'name' => 'C-10'],
            ['make_id' => 19, 'name' => 'Captiva'],
            ['make_id' => 19, 'name' => 'Corvette'],
            ['make_id' => 19, 'name' => 'Cruze'],
            ['make_id' => 19, 'name' => 'Orlando'],
            ['make_id' => 19, 'name' => 'Trailblazer'],

            // Hyundai cars
            ['make_id' => 20, 'name' => 'Accent'],
            ['make_id' => 20, 'name' => 'Atos'],
            ['make_id' => 20, 'name' => 'Avante'],
            ['make_id' => 20, 'name' => 'Azera'],
            ['make_id' => 20, 'name' => 'Bayon'],
            ['make_id' => 20, 'name' => 'Casper'],
            ['make_id' => 20, 'name' => 'Click'],
            ['make_id' => 20, 'name' => 'County'],
            ['make_id' => 20, 'name' => 'Creta'],
            ['make_id' => 20, 'name' => 'Dynasty'],
            ['make_id' => 20, 'name' => 'Elantra'],
            ['make_id' => 20, 'name' => 'Entourage'],
            ['make_id' => 20, 'name' => 'Eon'],
            ['make_id' => 20, 'name' => 'Equus'],
            ['make_id' => 20, 'name' => 'Excel'],
            ['make_id' => 20, 'name' => 'Galloper'],
            ['make_id' => 20, 'name' => 'Genesis'],
            ['make_id' => 20, 'name' => 'Getz'],
            ['make_id' => 20, 'name' => 'Grandeur'],
            ['make_id' => 20, 'name' => 'H1'],
            ['make_id' => 20, 'name' => 'H200'],
            ['make_id' => 20, 'name' => 'H300'],
            ['make_id' => 20, 'name' => 'I10'],
            ['make_id' => 20, 'name' => 'I20'],
            ['make_id' => 20, 'name' => 'I30'],
            ['make_id' => 20, 'name' => 'I40'],
            ['make_id' => 20, 'name' => 'Ioniq'],
            ['make_id' => 20, 'name' => 'IX35'],
            ['make_id' => 20, 'name' => 'Kona'],
            ['make_id' => 20, 'name' => 'Kona Electric'],
            ['make_id' => 20, 'name' => 'Marcia'],
            ['make_id' => 20, 'name' => 'Matrix'],
            ['make_id' => 20, 'name' => 'PanelPorte II'],
            ['make_id' => 20, 'name' => 'Polisade'],
            ['make_id' => 20, 'name' => 'S-Coupe'],
            ['make_id' => 20, 'name' => 'Santa Cruz'],
            ['make_id' => 20, 'name' => 'Santa Fe'],
            ['make_id' => 20, 'name' => 'Santamo'],
            ['make_id' => 20, 'name' => 'Satellite'],
            ['make_id' => 20, 'name' => 'Sonata'],
            ['make_id' => 20, 'name' => 'Starex'],
            ['make_id' => 20, 'name' => 'Staria'],
            ['make_id' => 20, 'name' => 'Stellar'],
            ['make_id' => 20, 'name' => 'Terracan'],
            ['make_id' => 20, 'name' => 'Triburon'],
            ['make_id' => 20, 'name' => 'Trajet'],
            ['make_id' => 20, 'name' => 'Tucson'],
            ['make_id' => 20, 'name' => 'Veloster'],
            ['make_id' => 20, 'name' => 'Venue'],
            ['make_id' => 20, 'name' => 'Veracruz'],
            ['make_id' => 20, 'name' => 'Verna'],
            ['make_id' => 20, 'name' => 'XG30'],
            ['make_id' => 20, 'name' => 'XG350'],
            // Kia cars
            ['make_id' => 21, 'name' => 'Sorento'],
            ['make_id' => 21, 'name' => 'Sportage'],

            // mini cars
            ['make_id' => 22, 'name' => 'Clubman'],
            ['make_id' => 22, 'name' => 'Convertible'],
            ['make_id' => 22, 'name' => 'Cooper'],
            ['make_id' => 22, 'name' => 'Countryman'],
            ['make_id' => 22, 'name' => 'Mini'],

            // Tesla cars
            ['make_id' => 23, 'name' => 'Y'],
            ['make_id' => 23, 'name' => 'Cybertruck'],
            ['make_id' => 23, 'name' => '3'],
            ['make_id' => 23, 'name' => 'S'],
            ['make_id' => 23, 'name' => 'X'],

            // Chrysler cars
            ['make_id' => 24, 'name' => 'PT Cruiser'],
            ['make_id' => 24, 'name' => 'Voyager'],
            ['make_id' => 24, 'name' => '200'],
            ['make_id' => 24, 'name' => '300'],
            ['make_id' => 24, 'name' => 'Crossfire'],
            ['make_id' => 24, 'name' => 'Concorde'],
            ['make_id' => 24, 'name' => 'Neon'],
            ['make_id' => 24, 'name' => 'Sebring'],
            ['make_id' => 24, 'name' => 'LeBaron'],
            ['make_id' => 24, 'name' => 'Pacifica'],
            ['make_id' => 24, 'name' => 'Aspen'],

            // RAM cars
            ['make_id' => 25, 'name' => 'RAM 1500'],
            ['make_id' => 25, 'name' => 'RAM 3500'],
            ['make_id' => 25, 'name' => 'RAM ProMaster 1500'],
            ['make_id' => 25, 'name' => 'RAM 1500 Classic'],
            ['make_id' => 25, 'name' => 'RAM ProMaster 3500'],
            ['make_id' => 25, 'name' => 'RAM ProMaster 2500 Window Van'],
            ['make_id' => 25, 'name' => 'RAM ProMaster 2500'],
            ['make_id' => 25, 'name' => 'RAM 2500'],
            ['make_id' => 25, 'name' => 'RAM ProMaster 3500 Window Van'],

            // GMC cars
            ['make_id' => 26, 'name' => 'sierra 1500'],
            ['make_id' => 26, 'name' => 'sierra hd'],
            ['make_id' => 26, 'name' => 'canyon'],
            ['make_id' => 26, 'name' => 'hummer ev pickup'],
            ['make_id' => 26, 'name' => 'sierra ev denali'],

            // Acura cars
            ['make_id' => 27, 'name' => 'ZDX 2024'],
            ['make_id' => 27, 'name' => 'RDX 2025'],
            ['make_id' => 27, 'name' => 'MDX 2025'],

            // Genesis cars
            ['make_id' => 28, 'name' => 'G90 Black'],
            ['make_id' => 28, 'name' => 'G90 Long Wheel Base'],
            ['make_id' => 28, 'name' => 'G90'],
            ['make_id' => 28, 'name' => 'G80'],
            ['make_id' => 28, 'name' => 'G70'],
            ['make_id' => 28, 'name' => 'G70 Shooting Brake'],
            ['make_id' => 28, 'name' => 'GV80'],
            ['make_id' => 28, 'name' => 'GV80 Coupe'],
            ['make_id' => 28, 'name' => 'GV70'],
            ['make_id' => 28, 'name' => 'Electrified GV70'],
            ['make_id' => 28, 'name' => 'GV60'],

            // Alfa Romeo cars
            ['make_id' => 29, 'name' => 'Giulia'],
            ['make_id' => 29, 'name' => 'MiTo'],

            // Fiat cars
            ['make_id' => 30, 'name' => 'Panda'],

            // Maserati cars
            ['make_id' => 31, 'name' => 'Levanti'],

            // Ferrari cars
            ['make_id' => 32, 'name' => 'Ferrari12Cilindri'],
            ['make_id' => 32, 'name' => 'Ferrari296'],
            ['make_id' => 32, 'name' => 'Ferrari812'],
            ['make_id' => 32, 'name' => 'Ferrari Daytona SP3'],
            ['make_id' => 32, 'name' => 'Ferrari f8 Tributo/Spider'],
            ['make_id' => 32, 'name' => 'Ferrari Roma'],

            // Lamborghini cars
            ['make_id' => 33, 'name' => 'Revuelto'],
            ['make_id' => 33, 'name' => 'Huracan'],
            ['make_id' => 33, 'name' => 'Urus SE'],
            ['make_id' => 33, 'name' => 'Urus S'],
            ['make_id' => 33, 'name' => 'Urus Performante'],
            ['make_id' => 33, 'name' => 'Sian Roadster'],
            ['make_id' => 33, 'name' => 'Sian FKP 37'],
            ['make_id' => 33, 'name' => 'Terzo millenio'],
            ['make_id' => 33, 'name' => 'Estoque'],

            // Aston Martin cars
            ['make_id' => 34, 'name' => 'DB12'],
            ['make_id' => 34, 'name' => 'Valhalla'],
            ['make_id' => 34, 'name' => 'Valkyrie'],
            ['make_id' => 34, 'name' => 'DBX'],
            ['make_id' => 34, 'name' => 'DB11'],
            ['make_id' => 34, 'name' => 'DB9 GT'],
            ['make_id' => 34, 'name' => 'DBS'],
            ['make_id' => 34, 'name' => 'One-77'],
            ['make_id' => 34, 'name' => 'Rapide'],

            // RollsRoyce cars
            ['make_id' => 35, 'name' => 'Ghost'],
            ['make_id' => 35, 'name' => 'Phantom'],

            // Bentley cars
            ['make_id' => 36, 'name' => 'Bentayga'],
            ['make_id' => 36, 'name' => 'Continental'],
            ['make_id' => 36, 'name' => 'S-Type'],

            // Pagani cars
            ['make_id' => 37, 'name' => 'Zonda c12'],
            ['make_id' => 37, 'name' => 'Zonda F'],
            ['make_id' => 37, 'name' => 'Zonda Roadster'],
            ['make_id' => 37, 'name' => 'Zonda R Clubsport'],
            ['make_id' => 37, 'name' => 'Huayra'],
            ['make_id' => 37, 'name' => 'Huayra BC'],
            ['make_id' => 37, 'name' => 'Huayra Imola'],
            ['make_id' => 37, 'name' => 'One-off Huayra'],

            //daihatsu models
            ['make_id' => 38, 'name' => 'Applause'],
            ['make_id' => 38, 'name' => 'Atrai'],
            ['make_id' => 38, 'name' => 'Boon'],
            ['make_id' => 38, 'name' => 'Cast'],
            ['make_id' => 38, 'name' => 'Copen'],
            ['make_id' => 38, 'name' => 'Cuore'],
            ['make_id' => 38, 'name' => 'Delta'],
            ['make_id' => 38, 'name' => 'Esse'],
            ['make_id' => 38, 'name' => 'Gran Move'],
            ['make_id' => 38, 'name' => 'Granmax'],
            ['make_id' => 38, 'name' => 'HIJET'],
            ['make_id' => 38, 'name' => 'Mira'],
            ['make_id' => 38, 'name' => 'Materia'],
            ['make_id' => 38, 'name' => 'Move'],
            ['make_id' => 38, 'name' => 'Move Canbus'],
            ['make_id' => 38, 'name' => 'Move Conte'],
            ['make_id' => 38, 'name' => 'Naked'],
            ['make_id' => 38, 'name' => 'Opti'],
            ['make_id' => 38, 'name' => 'Rocky'],
            ['make_id' => 38, 'name' => 'Sirion'],
            ['make_id' => 38, 'name' => 'Taft'],
            ['make_id' => 38, 'name' => 'Tanto'],
            ['make_id' => 38, 'name' => 'Terios'],
            ['make_id' => 38, 'name' => 'Thor'],
            ['make_id' => 38, 'name' => 'YRV'],
            ['make_id' => 38, 'name' => 'Charade'],
            ['make_id' => 38, 'name' => 'Charmant'],

            //datsun models
            ['make_id' => 39, 'name' => '1200'],
            ['make_id' => 39, 'name' => 'Cross'],
            ['make_id' => 39, 'name' => 'Go'],
            ['make_id' => 39, 'name' => 'Go Plus'],
            ['make_id' => 39, 'name' => 'mi-Do'],
            ['make_id' => 39, 'name' => 'on-Do'],
            ['make_id' => 39, 'name' => 'redi-Go'],
            ['make_id' => 39, 'name' => 'Violet'],
            //suzuki models
            ['make_id' => 40, 'name' => '250'],
            ['make_id' => 40, 'name' => 'Address'],
            ['make_id' => 40, 'name' => 'Alto'],
            ['make_id' => 40, 'name' => 'Aerio'],
            ['make_id' => 40, 'name' => 'AN'],
            ['make_id' => 40, 'name' => 'AP'],
            ['make_id' => 40, 'name' => 'B-King'],
            ['make_id' => 40, 'name' => 'Baleno'],
            ['make_id' => 40, 'name' => 'Bandit'],
            ['make_id' => 40, 'name' => 'Boost'],
            ['make_id' => 40, 'name' => 'Boulevard'],
            ['make_id' => 40, 'name' => 'Burgman'],
            ['make_id' => 40, 'name' => 'Cappuccino'],
            ['make_id' => 40, 'name' => 'CARRY TRUCK'],
            ['make_id' => 40, 'name' => 'Celerio'],
            ['make_id' => 40, 'name' => 'Cervo'],
            ['make_id' => 40, 'name' => 'Ciaz'],
            ['make_id' => 40, 'name' => 'Covie'],
            ['make_id' => 40, 'name' => 'DL'],
            ['make_id' => 40, 'name' => 'DR'],
            ['make_id' => 40, 'name' => 'DS'],
            ['make_id' => 40, 'name' => 'Dzire'],
            ['make_id' => 40, 'name' => 'Eeco'],
            ['make_id' => 40, 'name' => 'Equartor'],
            ['make_id' => 40, 'name' => 'Ertiga'],
            ['make_id' => 40, 'name' => 'Esteem'],
            ['make_id' => 40, 'name' => 'EV'],
            ['make_id' => 40, 'name' => 'Every Wagon'],
            ['make_id' => 40, 'name' => 'F1'],
            ['make_id' => 40, 'name' => 'Forenza'],
            ['make_id' => 40, 'name' => 'Fronte'],
            ['make_id' => 40, 'name' => 'Fronx'],
            ['make_id' => 40, 'name' => 'FX650'],
            ['make_id' => 40, 'name' => 'FXR'],
            ['make_id' => 40, 'name' => 'GN'],
            ['make_id' => 40, 'name' => 'GP'],
            ['make_id' => 40, 'name' => 'GR'],
            ['make_id' => 40, 'name' => 'Grad'],
            ['make_id' => 40, 'name' => 'Grand Vitara'],
            ['make_id' => 40, 'name' => 'GS'],
            ['make_id' => 40, 'name' => 'GSX'],
            ['make_id' => 40, 'name' => 'GT'],
            ['make_id' => 40, 'name' => 'GV'],
            ['make_id' => 40, 'name' => 'GX'],
            ['make_id' => 40, 'name' => 'Hayabusa'],
            ['make_id' => 40, 'name' => 'Hustler'],
            ['make_id' => 40, 'name' => 'Ignis'],
            ['make_id' => 40, 'name' => 'Impulse'],
            ['make_id' => 40, 'name' => 'Inazuma'],
            ['make_id' => 40, 'name' => 'Intruder'],
            ['make_id' => 40, 'name' => 'JR'],
            ['make_id' => 40, 'name' => 'Katana'],
            ['make_id' => 40, 'name' => 'Kei'],
            ['make_id' => 40, 'name' => 'Kizashi'],
            ['make_id' => 40, 'name' => 'Landy'],
            ['make_id' => 40, 'name' => 'Liana'],
            ['make_id' => 40, 'name' => 'Light'],
            ['make_id' => 40, 'name' => 'LJ'],
            ['make_id' => 40, 'name' => 'LS'],
            ['make_id' => 40, 'name' => 'Marauder'],
            ['make_id' => 40, 'name' => 'Maruti Omni'],
            ['make_id' => 40, 'name' => 'PV'],
            ['make_id' => 40, 'name' => 'RE'],
            ['make_id' => 40, 'name' => 'Reno'],
            ['make_id' => 40, 'name' => 'RM'],
            ['make_id' => 40, 'name' => 'RV'],
            ['make_id' => 40, 'name' => 'S-Presso'],
            ['make_id' => 40, 'name' => 'Samurai'],
            ['make_id' => 40, 'name' => 'Savage'],
            ['make_id' => 40, 'name' => 'SB'],
            ['make_id' => 40, 'name' => 'SC'],
            ['make_id' => 40, 'name' => 'SFV650'],
            ['make_id' => 40, 'name' => 'Shogun'],
            ['make_id' => 40, 'name' => 'Sidekick'],
            ['make_id' => 40, 'name' => 'Sierra'],
            ['make_id' => 40, 'name' => 'Solio'],
            ['make_id' => 40, 'name' => 'SP'],
            ['make_id' => 40, 'name' => 'Spacia'],
            ['make_id' => 40, 'name' => 'Splash'],
            ['make_id' => 40, 'name' => 'SR'],
            ['make_id' => 40, 'name' => 'ST'],
            ['make_id' => 40, 'name' => 'Street'],
            ['make_id' => 40, 'name' => 'Super Carry'],
            ['make_id' => 40, 'name' => 'SV'],
            ['make_id' => 40, 'name' => 'SV650SF'],
            ['make_id' => 40, 'name' => 'SX'],
            ['make_id' => 40, 'name' => 'Sx4'],
            ['make_id' => 40, 'name' => 'T'],
            ['make_id' => 40, 'name' => 'TC'],
            ['make_id' => 40, 'name' => 'TL'],
            ['make_id' => 40, 'name' => 'TR'],
            ['make_id' => 40, 'name' => 'TS'],
            ['make_id' => 40, 'name' => 'TU'],
            ['make_id' => 40, 'name' => 'US'],
            ['make_id' => 40, 'name' => 'V-Strom'],
            ['make_id' => 40, 'name' => 'Van'],
            ['make_id' => 40, 'name' => 'Verona'],
            ['make_id' => 40, 'name' => 'Vitara'],
            ['make_id' => 40, 'name' => 'Volty'],
            ['make_id' => 40, 'name' => 'VS'],
            ['make_id' => 40, 'name' => 'VX'],
            ['make_id' => 40, 'name' => 'Wagon'],
            ['make_id' => 40, 'name' => 'X-90'],
            ['make_id' => 40, 'name' => 'X2'],
            ['make_id' => 40, 'name' => 'XF'],
            ['make_id' => 40, 'name' => 'XL-6'],
            ['make_id' => 40, 'name' => 'XL-7'],


            //peugeot models

            ['make_id' => 41, 'name' => '1007'],
            ['make_id' => 41, 'name' => '104'],
            ['make_id' => 41, 'name' => '106'],
            ['make_id' => 41, 'name' => '107'],
            ['make_id' => 41, 'name' => '2008'],
            ['make_id' => 41, 'name' => '208'],
            ['make_id' => 41, 'name' => '301'],
            ['make_id' => 41, 'name' => '304'],
            ['make_id' => 41, 'name' => '306'],
            ['make_id' => 41, 'name' => '307'],
            ['make_id' => 41, 'name' => '308'],
            ['make_id' => 41, 'name' => '309'],
            ['make_id' => 41, 'name' => '403'],
            ['make_id' => 41, 'name' => '404'],
            ['make_id' => 41, 'name' => '405'],
            ['make_id' => 41, 'name' => '406'],
            ['make_id' => 41, 'name' => '407'],
            ['make_id' => 41, 'name' => '408'],
            ['make_id' => 41, 'name' => '5008'],
            ['make_id' => 41, 'name' => '504'],
            ['make_id' => 41, 'name' => '505'],
            ['make_id' => 41, 'name' => '604'],
            ['make_id' => 41, 'name' => '605'],
            ['make_id' => 41, 'name' => '607'],
            ['make_id' => 41, 'name' => '806'],
            ['make_id' => 41, 'name' => '807'],
            ['make_id' => 41, 'name' => '907'],
            ['make_id' => 41, 'name' => 'Boxer'],
            ['make_id' => 41, 'name' => 'C-Tech'],
            ['make_id' => 41, 'name' => 'Expert'],
            ['make_id' => 41, 'name' => 'Geopolis'],
            ['make_id' => 41, 'name' => 'Jet'],
            ['make_id' => 41, 'name' => 'JetForce'],
            ['make_id' => 41, 'name' => 'Kart'],
            ['make_id' => 41, 'name' => 'Landtrek'],
            ['make_id' => 41, 'name' => 'Partner'],
            ['make_id' => 41, 'name' => 'Rally'],
            ['make_id' => 41, 'name' => 'RC'],
            ['make_id' => 41, 'name' => 'Satelis'],
            ['make_id' => 41, 'name' => 'Sesame'],
            ['make_id' => 41, 'name' => 'Speedfight'],
            ['make_id' => 41, 'name' => 'Sum'],
            ['make_id' => 41, 'name' => 'V-CLIC'],
            ['make_id' => 41, 'name' => 'Vivacity'],
            ['make_id' => 41, 'name' => 'Vivacy'],
            ['make_id' => 41, 'name' => 'Vogue'],
            ['make_id' => 41, 'name' => 'XP'],
            ['make_id' => 41, 'name' => 'XR'],

            //isuzu models
            ['make_id' => 42, 'name' => 'Amigo'],
            ['make_id' => 42, 'name' => 'Ascender'],
            ['make_id' => 42, 'name' => 'Axiom'],
            ['make_id' => 42, 'name' => 'D-MAX'],
            ['make_id' => 42, 'name' => 'ELF Truck'],
            ['make_id' => 42, 'name' => 'Gemini'],
            ['make_id' => 42, 'name' => 'Hombre'],
            ['make_id' => 42, 'name' => 'I-Series'],
            ['make_id' => 42, 'name' => 'Impulse'],
            ['make_id' => 42, 'name' => 'KB'],
            ['make_id' => 42, 'name' => 'LB'],
            ['make_id' => 42, 'name' => 'Midi'],
            ['make_id' => 42, 'name' => 'MU-X'],
            ['make_id' => 42, 'name' => 'Oasis'],
            ['make_id' => 42, 'name' => 'Redeo'],
            ['make_id' => 42, 'name' => 'Stylus'],
            ['make_id' => 42, 'name' => 'Tougher'],
            ['make_id' => 42, 'name' => 'Trooper'],
            ['make_id' => 42, 'name' => 'VehiCross'],
        ];


        // Insert data into the car_models table
        foreach ($models as $model) {
            carModel::create($model);
        }
    }
}
